language: php

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.composer/cache/files

php:
  - 7.1
  - 7.2
  - 7.3

env:
  - ILLUMINATE_VERSION=5.5.* SOCIALITE_VERSION=^3.0 PHPUNIT_VERSION=^6.5.0 TESTBENCH_VERSION=^3.5.0
  - ILLUMINATE_VERSION=5.6.* SOCIALITE_VERSION=^3.0 PHPUNIT_VERSION=^7.5.0 TESTBENCH_VERSION=^3.6.0
  - ILLUMINATE_VERSION=5.7.* SOCIALITE_VERSION=^4.0 PHPUNIT_VERSION=^7.5.0 TESTBENCH_VERSION=^3.7.0
  - ILLUMINATE_VERSION=5.8.* SOCIALITE_VERSION=^4.0 PHPUNIT_VERSION=^7.5.0 TESTBENCH_VERSION=^3.8.0
  - ILLUMINATE_VERSION=6.0.* SOCIALITE_VERSION=^4.0 PHPUNIT_VERSION=^7.5.0 TESTBENCH_VERSION=^4.0.0 COVERAGE=true

matrix:
  exclude:
    - php: 7.1
      env: ILLUMINATE_VERSION=6.0.*

before_install:
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - cp ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ~/xdebug.ini
  - phpenv config-rm xdebug.ini
  - composer global require hirak/prestissimo --update-no-dev
  - composer require "illuminate/auth:${ILLUMINATE_VERSION}" "illuminate/contracts:${ILLUMINATE_VERSION}" "illuminate/database:${ILLUMINATE_VERSION}" "illuminate/http:${ILLUMINATE_VERSION}" "illuminate/support:${ILLUMINATE_VERSION}" "laravel/socialite:${SOCIALITE_VERSION}" "orchestra/testbench:${TESTBENCH_VERSION}" "orchestra/database:${TESTBENCH_VERSION}" "phpunit/phpunit:${PHPUNIT_VERSION}" --no-update --prefer-dist

install: travis_retry composer install --no-interaction --prefer-dist

before_script: phpenv config-add ~/xdebug.ini

script: composer test-with-coverage

after_success:
  - |
    if [[ $COVERAGE == true && ${TRAVIS_PHP_VERSION:0:3} == "7.3" ]]; then
      php vendor/bin/php-coveralls
    fi

notifications:
  email: false
